networks:
  laravel:


volumes:
  db-data:


services:
  php:
    container_name: php-fpm
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - database
    networks:
      - laravel

  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    environment:
      - UID=1000
      - GID=1000
    networks:
      - laravel
    depends_on:
      - php
      - database

  database:
    image: postgres:14
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=blog
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - laravel
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    ports:
      - "5050:80"
    depends_on:
      - database
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@test.com
      - PGADMIN_DEFAULT_PASSWORD=password
    networks:
      - laravel
